[influx_info]
url = "http://129.169.48.176:8086"
org = "Robot_Lab"
token =  "robot-lab-2023" 
bucket = "fault_monitoring" 
frequency_record_seconds = 1

[frepple_info]
URL = "http://129.169.48.176:9000"
password = "admin"
user ="admin"


[Factory]
name = "Manual Assembly" #"3D Printing"
machine = ["Robot_Cell_3_LRM", "Robot_Cell_3_M6", "Robot_track"]
frequencyUpdate = 1
fileType = ["AAS", "csv"]
first_check = 6500 #hours
address = "Robot Lab, Insitute for manufacturing, Cambridge, UK"
email = "sjb351@cam.ac.uk"
process = ["robotic assembly"]


[energy_use]
name = "energy use"
frequency= "per product" # per product, per order, per second
units= "kWh" #Units of the data, no impact on colelction
method= "tracking" # data collected using signal peaks (signals) or tracking system (tracking), MES or <sensor>-MES combination
machine_list = ["Screwdriver"]


[material_use]
name = "material use"
frequency= "per product" # per product, per order, per second
units= "kg" #Units of the data, no impact on colelction
method= "MES" # data collected using signal peaks (signals) or tracking system (tracking), MES or <sensor>-MES combination

[material_type]
name = "material type"
frequency= "per order" # per product, per order, per second
units= "kg" #Units of the data, no impact on colelction
method= "MES" # data collected using signal peaks (signals) or tracking system (tracking), MES or <sensor>-MES combination

[order_time_taken]
name = "order time taken"
frequency= "per order" # per product, per order, per second
method= "tracking" # data collected using signal peaks (signals) or tracking system (tracking), MES or <sensor>-MES combination
machine = ["Robot_Cell_3_LRM", "Robot_Cell_3_M6", "Robot_track"]
start_location = "Job Start"
end_location = "Job End"
# [assembly_method]
# name = "assembly method"
# frequency= "per order" # per product, per order, per second
# units= "kg" #Units of the data, no impact on colelction
# method= "MES" # data collected using signal peaks (signals) or tracking system (tracking), MES or <sensor>-MES combination
# add_to_AAS = 1


